### ISSUE TITLE
Console log in production environment

### ISSUE THREAD

**Issue by patrickLindell** [Queue-Fair/clientside#1]
Hi,
We use this script in one of our production environments and it makes logs to our console.
It seems to be this line https://github.com/Queue-Fair/clientside/blob/main/queue-fair-adapter-master.js#L58 that causes it. Here's the code:
```
	extractClientName() {
		let scriptTags=document.getElementsByTagName("script");
		for(let i=0; i<scriptTags.length; i++) {
			let t=scriptTags[i];
			let a = t.dataset;
			console.log(a); <-----
			let clientName=a["queueFairClient"];
```
Could you please remove it or hide it behind a debug check?

**Comment by Queue-Fair** [comment]
Hi there, we don't recommend you use the master.js in production - use the minified queue-fair-adapter.js instead.

**Comment by patrickLindell** [comment]
Yes I am using the minified version, but I thought it would be easier to point out the log in the non minified version. In the minified version it is transpiled into this: `for(let t=0;t<e.length;t++){let i=e[t],r=i.dataset;console.log(r);`

**Comment by Queue-Fair** [comment]
Ah OK! Thank you.  The console.log has been removed from both files.

Have a great day!

**Comment by patrickLindell** [comment]
Great! 🎉
